# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'RastreoGpsMovil' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RastreoGpsMovil
  pod "WARangeSlider"
  pod "AppCenter"
  pod "SwiftyGif"
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  
end
